# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
#
#  
# Example 1:
#
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
#
# Example 2:
#
#
# Input: s = "", t = "y"
# Output: "y"
#
#
# Example 3:
#
#
# Input: s = "a", t = "aa"
# Output: "a"
#
#
# Example 4:
#
#
# Input: s = "ae", t = "aea"
# Output: "a"
#
#
#  
# Constraints:
#
#
# 	0 <= s.length <= 1000
# 	t.length == s.length + 1
# 	s and t consist of lower-case English letters.
#
#


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        letters = {}
        tLetters = list(t)
        sLetters = list(s)
        for char in sLetters:
            if char in letters:
                letters[char] += 1
            else:
                letters[char] = 1
        for char in tLetters:
            if char not in letters:
                return char
            else:
                letters[char] -= 1
        
        for k,v in letters.items():
            if v != 0:
                return k
